### PR TITLE
Add DynamicMavenProjectFactory to deal with tycho-pomless

### PR DESCRIPTION
**Pull request by kysmith-csg**
This is my attempt of solving #55. During the Maven import it checks if the pom.xml filename from m2e **isn't** `pom.xml` (it can be many things with Tycho). If so, it uses that as the `pom.xml` instead. Obviously tested with my local setup and it is able to import the projects.

This is my first time doing anything with the Oomph codebase, so apologies if I didn't do something right.

### CODE REVIEW

**Comment by merks** [comment]
This looks promising. I'd like to understand better how this works.  Is there some public repository that I can look at to see how what you're adding works in action?

**Comment by kysmith-csg** [comment]
@merks I made an example project here https://github.com/kysmith-csg/oomph-dynamicfactory-demo.

**Comment by merks** [comment]
Great! I will try to find some time tomorrow morning.

**Comment by merks** [comment]
@kysmith-csg 

I amended your commit with some minor improvements.  But I wasn't sure how to push that back to your clone where the commit was on maser not on a topic branch so I created this new pull request:

https://github.com/eclipse-oomph/oomph/pull/62

I will close this one because all your changes are also on that PR.

**Pull request closed without merging**
